# Regression dataset
Here I load the Titanic dataset which predicts  the passange survival

In [1]:
using DataFrames

## 1. Load a dataset  as a dataframe and  convert it to a julia array

In [2]:
df = readtable("Titanic.csv", header=true)
df[:,:PClassCode] = zeros(Int,1313)
df[df[:,:PClass].=="1st",:PClassCode] = 1
df[df[:,:PClass].=="2nd",:PClassCode] = 2
df[df[:,:PClass].=="3rd",:PClassCode] = 3
delete!(df, :x)
delete!(df, :Name)
delete!(df, :Sex)
delete!(df, :PClass)
deleterows!(df,find(isna(df[:,:Age])))
df[end+1]=df[:,:Survived]
delete!(df, :Survived)
data = convert(Array, df)

756x4 Array{Real,2}:
 29.0   1  1  1
  2.0   1  1  0
 30.0   0  1  0
 25.0   1  1  0
  0.92  0  1  1
 47.0   0  1  1
 63.0   1  1  1
 39.0   0  1  0
 58.0   1  1  1
 71.0   0  1  0
 47.0   0  1  0
 19.0   1  1  1
 50.0   1  1  1
  ⋮            
 45.0   1  3  1
 28.0   0  3  0
 21.0   0  3  0
 27.0   0  3  0
 36.0   0  3  0
 27.0   0  3  0
 15.0   1  3  1
 27.0   0  3  0
 26.0   0  3  0
 22.0   0  3  0
 24.0   0  3  0
 29.0   0  3  0

## 2.  Get x and  y subset

In [3]:
x = data[:,1:end-1]
y = data[:,end]

756-element Array{Real,1}:
 1
 0
 0
 0
 1
 1
 1
 0
 1
 0
 0
 1
 1
 ⋮
 1
 0
 0
 0
 0
 0
 1
 0
 0
 0
 0
 0

## 3. Shuffel Divide into a training and a test subset

In [4]:
index = shuffle!(collect(1:size(y,1)))
i_train = index[1:round(Int,length(index)*0.6)]
i_test = index[round(Int,length(index)*0.6)+1:end]
y_train = y[i_train]
y_test = y[i_test]
x_train = x[i_train,:]
x_test = x[i_test,:]

302x3 Array{Real,2}:
 41.0  0  3
 24.0  0  3
 25.0  0  3
 20.0  0  3
 23.0  0  3
 29.0  1  1
 41.0  0  3
 48.0  1  3
 18.0  0  2
 27.0  0  3
 27.0  0  2
 49.0  1  2
 24.0  0  3
  ⋮        
 60.0  1  1
 28.0  0  3
 58.0  1  1
 19.0  0  3
 56.0  0  1
 44.0  0  1
 36.0  0  1
 39.0  0  3
 30.0  0  2
 24.0  1  3
 20.0  0  3
 55.0  1  1